### ISSUE TITLE
process exited with code 4294967295

### ISSUE THREAD

**Issue by MatinDehghanian** [ALIILAPRO/spotify-account-creator#6]
```
‍‍‍‍Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 381, in _make_request
  File "urllib3\connectionpool.py", line 978, in _validate_conn
  File "urllib3\connection.py", line 397, in connect
  File "urllib3\connection.py", line 407, in _match_hostname
  File "ssl.py", line 416, in match_hostname
ssl.SSLCertVerificationError: ("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xcoder.fun', port=443): Max retries exceeded with url: /p.php?r=y (Caused by SSLError(SSLCertVerificationError("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spotify-reg.py", line 142, in <module>
  File "spotify-reg.py", line 72, in __init__
  File "spotify-reg.py", line 55, in getproxy
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='xcoder.fun', port=443): Max retries exceeded with url: /p.php?r=y (Caused by SSLError(SSLCertVerificationError("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'")))
[15352] Failed to execute script spotify-reg

[process exited with code 4294967295]‍

**Comment by ALIILAPRO** [comment]
> ```
> ‍‍‍‍Traceback (most recent call last):
>   File "urllib3\connectionpool.py", line 670, in urlopen
>   File "urllib3\connectionpool.py", line 381, in _make_request
>   File "urllib3\connectionpool.py", line 978, in _validate_conn
>   File "urllib3\connection.py", line 397, in connect
>   File "urllib3\connection.py", line 407, in _match_hostname
>   File "ssl.py", line 416, in match_hostname
> ssl.SSLCertVerificationError: ("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'",)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "requests\adapters.py", line 439, in send
>   File "urllib3\connectionpool.py", line 726, in urlopen
>   File "urllib3\util\retry.py", line 446, in increment
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='xcoder.fun', port=443): Max retries exceeded with url: /p.php?r=y (Caused by SSLError(SSLCertVerificationError("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'")))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "spotify-reg.py", line 142, in <module>
>   File "spotify-reg.py", line 72, in __init__
>   File "spotify-reg.py", line 55, in getproxy
>   File "requests\api.py", line 76, in get
>   File "requests\api.py", line 61, in request
>   File "requests\sessions.py", line 530, in request
>   File "requests\sessions.py", line 643, in send
>   File "requests\adapters.py", line 514, in send
> requests.exceptions.SSLError: HTTPSConnectionPool(host='xcoder.fun', port=443): Max retries exceeded with url: /p.php?r=y (Caused by SSLError(SSLCertVerificationError("hostname 'xcoder.fun' doesn't match either of '*.parkingcrew.net', 'parkingcrew.net'")))
> [15352] Failed to execute script spotify-reg
> 
> [process exited with code 4294967295]‍
> ```

soon fixed.
