### ISSUE TITLE
create GUI

### ISSUE THREAD

**Issue by Mohammadgeek** [ALIILAPRO/spotify-account-creator#7]
سلام به نظرم داشتن یک رابط گرافیکی توی توسعه اش خیلی میتونه کمک کننده باشه و یک باتن که هر بار کاربر بتونه ایمیل و رمز به شکل پاپ آپ دریافت کنه و نخواد اسکریپ بزنه

**Comment by ALIILAPRO** [comment]
سلام ممنون از شما رابط گرافیکی این پروژه اضافه شد.
