### ISSUE TITLE
facing an error when trying to make account

### ISSUE THREAD

**Issue by SalehKiani** [ALIILAPRO/spotify-account-creator#9]
the code gets 302 status code error and the problem is that spotify founds out that the code is using a proxy server and doesn't let the request be done!

**Comment by Lukas-drz** [comment]
Yes, you have to use a proxy that's not spotted by Spotify, you should use residential proxies for example.

**Comment by ALIILAPRO** [comment]
> the code gets 302 status code error and the problem is that spotify founds out that the code is using a proxy server and doesn't let the request be done!

Try using VPN service. Like Proton VPN.
